---
title: "Difference in Gender Inequality Index by Country"
output: html_notebook
---



```{r}
library(countrycode)
library(usethis)
library(rmarkdown)
library(knitr)
library(tinytex)
library(here)
library(tidyverse)
library(broom)
library(sf)
library(fs)
library(janitor)
library(tmap)
library(tmaptools)
library(ggplot2)
```


```{r}

#read in world countries simple features
world_countries <- read_sf(here("World_Countries_(Generalized)_9029012925078512962.geojson"))

# read in inequality data
inequality <- read_csv(here("HDR23-24_Composite_indices_complete_time_series.csv"))

# create data frame of just what we need
inequality_2010_2019 <- select(inequality, country, iso3, gii_2019, gii_2010)

# create column for difference in gii
inequality_2010_2019 <- inequality_2010_2019 %>%
  clean_names(.,) %>%
  rename(., iso = iso3) %>%
  select(iso, gii_2019, gii_2010) %>%
  mutate(., difference = gii_2019 - gii_2010)

# clean names world_countries
world_countries <- clean_names(world_countries)

# change country code in world countries to iso3
world_countries$iso <- countrycode(world_countries$iso, "iso2c", "iso3c")

# join data
world_countries_difference_gii <- left_join(world_countries, inequality_2010_2019, by="iso")

# plot data
qtm(world_countries_difference_gii,
    fill="difference",
    fill.n=10,
    fill.style="kmeans",
    midpoint= 0,
    borders = NULL)

ggplot(world_countries_difference_gii, aes(fill = difference)) +
  geom_sf() +
  scale_fill_gradient2("Difference in Points",   low = "green",
  mid = "white",
  high = "red",
  midpoint = 0,) +
  theme_minimal() +
  labs(
    title = "Difference in Gender Inequality Index, 2010-2019",
    subtitle = "UN Human Development Reports",
    caption = "Lower score correlates with lower inequality. \nSource: https://hdr.undp.org/data-center/documentation-and-downloads"
  )  
```

These show the change in gender equality by country, as measured by Gender Inequality Index.

